package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/v-pat/fiberforge/internal/schema"
)

// AddModel incrementally adds a single model to an existing project without wiping existing code.
func AddModel(targetDir string, m schema.Model) error {
	_, err := AddModelWithOptions(targetDir, m, false)
	return err
}

// AddModelWithOptions incrementally adds a model with optional dry-run mode. Returns affected file paths.
func AddModelWithOptions(targetDir string, m schema.Model, dryRun bool) ([]string, error) {
	schemaPath := filepath.Join(targetDir, "fiberforge.yaml")
	cfg, err := schema.Load(schemaPath)
	if err != nil {
		// If schema file doesn't exist, try loading from root
		cfg, err = schema.Load("fiberforge.yaml")
		if err != nil {
			return nil, fmt.Errorf("could not find fiberforge.yaml in %s or workspace: %w", targetDir, err)
		}
	}

	cfg.OutputDir = targetDir

	// Check if model already exists
	for _, existing := range cfg.Models {
		if strings.EqualFold(existing.Name, m.Name) {
			return nil, fmt.Errorf("model %q already exists in schema", m.Name)
		}
	}

	if m.Endpoint == "" {
		m.Endpoint = strings.ToLower(schema.Plural(m.Name))
	}

	name := strings.ToLower(schema.Pascal(m.Name))
	var files []string

	// Track files to be created
	files = append(files, filepath.Join("model", name+".go"))
	files = append(files, filepath.Join("service", name+"_service.go"))
	files = append(files, filepath.Join("controller", name+"_controller.go"))

	if cfg.Features.Migrations && cfg.Database != "mongodb" {
		seq := len(cfg.Models) + 1
		migName := fmt.Sprintf("%06d_%s", seq, name)
		files = append(files, filepath.Join("migrations", migName+".up.sql"))
		files = append(files, filepath.Join("migrations", migName+".down.sql"))
	}

	if cfg.Features.Testing {
		files = append(files, filepath.Join("controller", name+"_test.go"))
	}

	files = append(files, filepath.Join("routes", "routes.go")+" (AST edit)")

	if dryRun {
		return files, nil
	}

	// Append model to schema config
	cfg.Models = append(cfg.Models, m)
	eng := New(cfg)

	// 1. Generate model file
	tmpl := modelTemplate
	if eng.isMongo() {
		tmpl = mongoModelTemplate
	}
	mm := eng.modelData(m)
	modelContent, err := eng.render("model", tmpl, mm)
	if err != nil {
		return nil, fmt.Errorf("failed to render model: %w", err)
	}
	if err := eng.write(filepath.Join("model", name+".go"), modelContent); err != nil {
		return nil, err
	}

	// 2. Generate service file
	prefix := "// Code generated by fiberforge. DO NOT EDIT.\n\n"
	svcTmpl := serviceTemplate
	if eng.isMongo() {
		svcTmpl = mongoServiceTemplate
	}
	svcContent, err := eng.render("service", svcTmpl, map[string]any{
		"AppName": eng.AppModule(),
		"Name":    schema.Pascal(m.Name),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to render service: %w", err)
	}
	if err := eng.write(filepath.Join("service", name+"_service.go"), prefix+svcContent); err != nil {
		return nil, err
	}

	// 3. Generate controller file
	ctrlTmpl := controllerTemplate
	if eng.isMongo() {
		ctrlTmpl = mongoControllerTemplate
	}
	ctrlContent, err := eng.render("controller", ctrlTmpl, map[string]any{
		"AppName":  eng.AppModule(),
		"Name":     schema.Pascal(m.Name),
		"Endpoint": m.Endpoint,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to render controller: %w", err)
	}
	if err := eng.write(filepath.Join("controller", name+"_controller.go"), prefix+ctrlContent); err != nil {
		return nil, err
	}

	// 4. Generate migration if enabled
	if cfg.Features.Migrations && !eng.isMongo() {
		driver := eng.dbDriver()
		up, down := buildMigration(m, driver)
		seq := len(cfg.Models)
		migName := fmt.Sprintf("%06d_%s", seq, name)
		_ = eng.write(filepath.Join("migrations", migName+".up.sql"), up)
		_ = eng.write(filepath.Join("migrations", migName+".down.sql"), down)
	}

	// 5. Generate test if enabled
	if cfg.Features.Testing {
		testContent, err := eng.render("controllertest", controllerTestTemplate, map[string]any{
			"AppName":  eng.AppModule(),
			"Name":     schema.Pascal(m.Name),
			"Endpoint": m.Endpoint,
		})
		if err == nil {
			_ = eng.write(filepath.Join("controller", name+"_test.go"), prefix+testContent)
		}
	}

	// 6. Inject route into routes/routes.go via AST
	routesFile := filepath.Join(targetDir, "routes", "routes.go")
	if _, err := os.Stat(routesFile); err == nil {
		if err := RegisterRouteInAST(routesFile, m, cfg.Features.Auth); err != nil {
			return nil, fmt.Errorf("failed to inject route into %s: %w", routesFile, err)
		}
	}

	// 7. Save updated fiberforge.yaml
	updatedYaml, err := yaml.Marshal(cfg)
	if err == nil {
		_ = os.WriteFile(filepath.Join(targetDir, "fiberforge.yaml"), updatedYaml, 0o644)
	}

	return files, nil
}
