package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/v-pat/fiberforge/internal/schema"
)

// PublicModules are the absolute paths from where generation writes files.
// Kept simple: everything is written under the output directory.

// Generate produces the entire project on disk. It returns the output
// directory on success.
func (e *Engine) Generate() (string, error) {
	if err := e.prepareDir(); err != nil {
		return "", err
	}
	if e.cfg.Features.Auth {
		e.ensureUserModel()
	}

	steps := []struct {
		name string
		fn   func() error
	}{
		{"project metadata", e.genProjectMeta},
		{"models", e.genModels},
		{"database", e.genDatabase},
		{"services", e.genServices},
		{"controllers", e.genControllers},
		{"auth", e.genAuth},
		{"routes", e.genRoutes},
		{"main", e.genMain},
		{"config", e.genConfig},
		{"migrations", e.genMigrations},
		{"support", e.genSupport},
		{"testing", e.genTesting},
		{"swagger", e.genSwagger},
	}

	for _, st := range steps {
		if err := st.fn(); err != nil {
			return "", fmt.Errorf("%s: %w", st.name, err)
		}
	}
	return e.dir, nil
}

// prepareDir creates the output directory cleanly if it doesn't exist.
func (e *Engine) prepareDir() error {
	return os.MkdirAll(e.dir, 0o755)
}

// ensureUserModel adds a minimal User model if the auth feature is enabled and
// the user did not already define one. It must run before all generators so the
// model participates in migration and CRUD wiring.
func (e *Engine) ensureUserModel() {
	for _, m := range e.cfg.Models {
		if strings.EqualFold(m.Name, "user") {
			return
		}
	}
	e.cfg.Models = append(e.cfg.Models, schema.Model{
		Name:     "User",
		Endpoint: "users",
		Fields: []schema.Field{
			{Name: "Email", Type: schema.TypeString, Required: true, Unique: true, Validation: "email"},
			{Name: "Password", Type: schema.TypePassword, Required: true, Sensitive: true},
		},
	})
}

// genProjectMeta writes go.mod, README, .gitignore and .env.example.
func (e *Engine) genProjectMeta() error {
	module := e.AppModule()
	data := struct {
		Module     string
		Driver     string
		Mongo      bool
		SQL        bool
		Auth       bool
		Migrations bool
	}{module, e.dbDriver(), e.isMongo(), !e.isMongo(), e.cfg.Features.Auth, e.cfg.Features.Migrations && !e.isMongo()}

	mod, err := e.render("gomod", goModTemplate, data)
	if err != nil {
		return err
	}
	if err := e.write("go.mod", mod); err != nil {
		return err
	}

	readme, err := e.renderReadme()
	if err != nil {
		return err
	}
	if err := e.write("README.md", readme); err != nil {
		return err
	}
	if err := e.write(".gitignore", gitignoreTemplate); err != nil {
		return err
	}

	env, err := e.renderEnv()
	if err != nil {
		return err
	}
	if err := e.write(".env.example", env); err != nil {
		return err
	}

	// Write fiberforge.yaml into generated project root
	yamlData, err := yaml.Marshal(e.cfg)
	if err == nil {
		_ = e.write("fiberforge.yaml", string(yamlData))
	}
	return nil
}

// genModels writes one model file per configured model.
func (e *Engine) genModels() error {
	tmpl := modelTemplate
	if e.isMongo() {
		tmpl = mongoModelTemplate
	}
	for _, m := range e.cfg.Models {
		mm := e.modelData(m)
		content, err := e.render("model", tmpl, mm)
		if err != nil {
			return err
		}
		if err := e.write(filepath.Join("model", strings.ToLower(schema.Pascal(m.Name))+".go"), content); err != nil {
			return err
		}
	}
	return nil
}

// genDatabase writes the database connection package.
func (e *Engine) genDatabase() error {
	if e.isMongo() {
		return e.write(filepath.Join("databases", "db.go"), mongoDBTemplate)
	}
	driver := e.dbDriver()
	data := struct {
		AppName string
		Driver  string
		Format  string
		Models  []string
	}{
		AppName: e.AppModule(),
		Driver:  driver,
		Format:  dsnFormat(driver),
		Models:  e.modelPascalNames(),
	}
	return e.write(filepath.Join("databases", "db.go"), sqlDBTemplate(data, e))
}

// genServices writes one service file per model.
func (e *Engine) genServices() error {
	prefix := "// Code generated by fiberforge. DO NOT EDIT.\n\n"
	extra := ""
	if e.cfg.Features.Auth {
		extra = authUserServiceTemplate
		if e.isMongo() {
			extra = mongoAuthUserServiceTemplate
		}
	}
	for _, m := range e.cfg.Models {
		if e.cfg.Features.Auth && strings.EqualFold(m.Name, "user") {
			continue
		}
		tmpl := serviceTemplate
		if e.isMongo() {
			tmpl = mongoServiceTemplate
		}
		content, err := e.render("service", tmpl, map[string]any{
			"AppName": e.AppModule(),
			"Name":    schema.Pascal(m.Name),
		})
		if err != nil {
			return err
		}
		if err := e.write(filepath.Join("service", strings.ToLower(schema.Pascal(m.Name))+"_service.go"), prefix+content); err != nil {
			return err
		}
	}
	if extra != "" {
		content, err := e.render("authuserservice", extra, map[string]any{"AppName": e.AppModule()})
		if err != nil {
			return err
		}
		return e.write(filepath.Join("service", "user_service.go"), prefix+content)
	}
	return nil
}

// genControllers writes one controller file per model.
func (e *Engine) genControllers() error {
	prefix := "// Code generated by fiberforge. DO NOT EDIT.\n\n"
	for _, m := range e.cfg.Models {
		if e.cfg.Features.Auth && strings.EqualFold(m.Name, "user") {
			continue
		}
		tmpl := controllerTemplate
		if e.isMongo() {
			tmpl = mongoControllerTemplate
		}
		content, err := e.render("controller", tmpl, map[string]any{
			"AppName":  e.AppModule(),
			"Name":     schema.Pascal(m.Name),
			"Endpoint": m.Endpoint,
		})
		if err != nil {
			return err
		}
		if err := e.write(filepath.Join("controller", strings.ToLower(schema.Pascal(m.Name))+"_controller.go"), prefix+content); err != nil {
			return err
		}
	}

	utilsContent, err := e.render("controller_utils", controllerUtilsTemplate, map[string]any{
		"AppName": e.AppModule(),
	})
	if err != nil {
		return err
	}
	if err := e.write(filepath.Join("controller", "utils.go"), prefix+utilsContent); err != nil {
		return err
	}

	return nil
}

// genAuth writes the auth package, user model integration and JWT middleware.
func (e *Engine) genAuth() error {
	if !e.cfg.Features.Auth {
		return nil
	}
	prefix := "// Code generated by fiberforge. DO NOT EDIT.\n\n"

	files := map[string]string{
		"auth/password.go": authPasswordTemplate,
	}
	if e.isMongo() {
		files["auth/jwt.go"] = mongoAuthJWTTemplate
		files["auth/store.go"] = mongoAuthStoreTemplate
	} else {
		files["auth/jwt.go"] = authJWTTemplate
		files["auth/store.go"] = authStoreTemplate
	}
	for rel, tmpl := range files {
		content, err := e.render("authfile", tmpl, map[string]any{"AppName": e.AppModule()})
		if err != nil {
			return err
		}
		if err := e.write(rel, prefix+content); err != nil {
			return err
		}
	}

	mwTmpl := middlewareTemplate
	if e.isMongo() {
		mwTmpl = mongoMiddlewareTemplate
	}
	mw, err := e.render("middleware", mwTmpl, map[string]any{"AppName": e.AppModule()})
	if err != nil {
		return err
	}
	if err := e.write(filepath.Join("middleware", "jwt.go"), prefix+mw); err != nil {
		return err
	}

	acTmpl := authControllerTemplate
	if e.isMongo() {
		acTmpl = mongoAuthControllerTemplate
	}
	ac, err := e.render("authcontroller", acTmpl, map[string]any{"AppName": e.AppModule()})
	if err != nil {
		return err
	}
	return e.write(filepath.Join("controller", "auth_controller.go"), prefix+ac)
}

// genRoutes writes the central routes file.
func (e *Engine) genRoutes() error {
	var groups []routeGroup
	for _, m := range e.cfg.Models {
		if strings.EqualFold(m.Name, "user") && e.cfg.Features.Auth {
			continue
		}
		groups = append(groups, routeGroup{
			Name: schema.Pascal(m.Name),
			Path: m.Endpoint,
			Var:  schema.Camel(m.Name) + "Group",
			Auth: e.cfg.Features.Auth && m.AuthProtected,
		})
	}
	content, err := e.render("routes", routesTemplate, map[string]any{
		"AppName":     e.AppModule(),
		"AuthEnabled": e.cfg.Features.Auth,
		"Groups":      groups,
	})
	if err != nil {
		return err
	}
	return e.write(filepath.Join("routes", "routes.go"), content)
}

// genMain writes main.go.
func (e *Engine) genMain() error {
	content, err := e.render("main", mainTemplate, map[string]any{
		"AppName":   e.AppModule(),
		"Port":      fmt.Sprintf("%d", e.cfg.Port),
		"Config":    true,
		"Logging":   e.cfg.Features.Logging,
		"Recover":   true,
		"Helmet":    true,
		"CORS":      e.cfg.Features.CORS,
		"RateLimit": e.cfg.Features.RateLimit,
	})
	if err != nil {
		return err
	}
	return e.write("main.go", content)
}

// genConfig writes the config loader package.
func (e *Engine) genConfig() error {
	content, err := e.render("config", configTemplate, map[string]any{
		"AppName":    e.cfg.AppName,
		"Port":       fmt.Sprintf("%d", e.cfg.Port),
		"DBPort":     dbPort(e.cfg.Database),
		"DBUser":     dbUser(e.cfg.Database),
		"DBPassword": dbPassword(e.cfg.Database),
	})
	if err != nil {
		return err
	}
	return e.write(filepath.Join("config", "config.go"), content)
}

// genMigrations writes golang-migrate migration files and runner (SQL DBs).
func (e *Engine) genMigrations() error {
	if !e.cfg.Features.Migrations || e.isMongo() {
		return nil
	}
	driver := e.dbDriver()
	for i, m := range e.cfg.Models {
		up, down := buildMigration(m, driver)
		name := fmt.Sprintf("%06d_%s", i+1, strings.ToLower(schema.Pascal(m.Name)))
		if err := e.write(filepath.Join("migrations", name+".up.sql"), up); err != nil {
			return err
		}
		if err := e.write(filepath.Join("migrations", name+".down.sql"), down); err != nil {
			return err
		}
	}
	return nil
}

// genSupport writes Docker, Makefile and CI files based on feature flags.
func (e *Engine) genSupport() error {
	if e.cfg.Features.Docker {
		if err := e.write("Dockerfile", dockerfileContent(e)); err != nil {
			return err
		}
		if err := e.write("docker-compose.yml", dockerComposeContent(e)); err != nil {
			return err
		}
	}
	if e.cfg.Features.CI {
		if err := e.write(filepath.Join(".github", "workflows", "ci.yml"), ciContent(e)); err != nil {
			return err
		}
	}
	if e.cfg.Features.Docker || e.cfg.Features.Migrations {
		makefile := makefileContent(e)
		if err := e.write("Makefile", makefile); err != nil {
			return err
		}
	}
	return nil
}

// genTesting writes test files when the testing feature is enabled.
func (e *Engine) genTesting() error {
	if !e.cfg.Features.Testing {
		return nil
	}
	prefix := "// Code generated by fiberforge. DO NOT EDIT.\n\n"
	for _, m := range e.cfg.Models {
		if strings.EqualFold(m.Name, "user") && e.cfg.Features.Auth {
			continue
		}
		content, err := e.render("controllertest", controllerTestTemplate, map[string]any{
			"AppName":  e.AppModule(),
			"Name":     schema.Pascal(m.Name),
			"Endpoint": m.Endpoint,
		})
		if err != nil {
			return err
		}
		if err := e.write(filepath.Join("controller", strings.ToLower(schema.Pascal(m.Name))+"_test.go"), prefix+content); err != nil {
			return err
		}
	}
	if e.cfg.Features.Auth {
		content, err := e.render("authtest", authTestTemplate, map[string]any{"AppName": e.AppModule()})
		if err != nil {
			return err
		}
		if err := e.write(filepath.Join("controller", "auth_test.go"), prefix+content); err != nil {
			return err
		}
	}
	return nil
}

// genSwagger writes swagger.json when the feature is enabled.
func (e *Engine) genSwagger() error {
	if !e.cfg.Features.Swagger {
		return nil
	}
	var models []swaggerModel
	for i, m := range e.cfg.Models {
		if strings.EqualFold(m.Name, "user") && e.cfg.Features.Auth {
			continue
		}
		models = append(models, swaggerModel{
			Name:     schema.Pascal(m.Name),
			Endpoint: m.Endpoint,
			Last:     i == len(e.cfg.Models)-1,
		})
	}
	for i := range models {
		models[i].Last = i == len(models)-1
	}
	content, err := e.render("swagger", swaggerJSONTemplate, map[string]any{
		"AppName": e.AppModule(),
		"Models":  models,
		"Auth":    e.cfg.Features.Auth,
	})
	if err != nil {
		return err
	}
	return e.write(filepath.Join("docs", "swagger.json"), content)
}
