package templates

// GoModTemplate renders the go.mod for the generated project.
const GoModTemplate = `module {{.Module}}

go 1.23

require (
	github.com/gofiber/fiber/v2 v2.52.4
	{{if .SQL}}gorm.io/gorm v1.25.10
	{{if .Driver}}gorm.io/driver/{{.Driver}} v1.5.6
	{{end}}{{end}}{{if .Mongo}}github.com/kamva/mgm/v3 v3.5.0
	go.mongodb.org/mongo-driver v1.15.1
	{{end}}{{if .Auth}}github.com/golang-jwt/jwt/v5 v5.2.1
	golang.org/x/crypto v0.23.0
	{{end}}{{if .Migrations}}github.com/golang-migrate/migrate/v4 v4.17.1
	{{end}}
)
`

// READMETemplate renders a short project README.
const READMETemplate = `# {{.AppName}}

A Go Fiber backend generated by FiberForge.

## Requirements

- Go 1.23+
- {{.DbName}} running locally (or via docker-compose)

## Getting started

1. Copy .env.example to .env and set connection values.
2. Run: go mod tidy, then: go run .
3. Server starts on port {{.Port}}.

## Endpoints

{{if .Auth}}- POST /api/auth/register
- POST /api/auth/login
- GET  /api/auth/me (protected)
{{end}}{{range .Models}}
- CRUD on /api/{{.Endpoint}}
{{end}}

## Makefile tasks

- make run — run the server
- make test — run tests
- make docker — build & run with docker-compose
`

// GitignoreTemplate renders a .gitignore for the generated project.
const GitignoreTemplate = `.env
bin/
*.exe
coverage.out
`
